export type DataClassification = "Actual" | "Estimated" | "Sample" | "Analyst assumption";
export type DealStage = "Idea" | "Initial Review" | "Valuation" | "Due Diligence" | "Financing" | "Pitch Preparation" | "Management Review" | "Negotiation" | "Announced" | "Closed" | "Passed";
export interface CompanyFinancials { name:string; ticker:string; sharePrice:number; dilutedShares:number; cash:number; debt:number; minorityInterest:number; preferredStock:number; revenue:number; ebitda:number; ebit:number; netIncome:number; freeCashFlow:number; growthRates:number[]; classification:DataClassification }
export interface ComparableCompany { company:string; ticker:string; marketCap:number; enterpriseValue:number; revenue:number; ebitda:number; revenueGrowth:number; epsGrowth:number; pe:number; roic:number; netDebt:number; strength:"Strong"|"Moderate"|"Weak"|"Excluded"; exclusionReason?:string }
export interface PrecedentTransaction { announcementDate:string; buyer:string; target:string; industry:string; transactionValue:number; enterpriseValue:number; revenue:number; ebitda:number; premium:number; paymentMethod:string; status:string; rationale:string; similarity:number }
export interface DcfAssumptions { revenue:number; growthRates:number[]; ebitdaMargins:number[]; taxRate:number; depreciation:number; capex:number; changeNwc:number; wacc:number; terminalGrowth:number; exitMultiple:number; netDebt:number; dilutedShares:number }
export interface DebtInstrument { instrument:string; principal:number; interestRate:number; maturity:string; amortization:number; secured:boolean; rateType:"Fixed"|"Floating" }
export interface CapitalStructure { cash:number; debt:DebtInstrument[]; preferredEquity:number; commonEquity:number }
export interface SourcesAndUses { sources:Record<string,number>; uses:Record<string,number> }
export interface MergerScenario { buyer:CompanyFinancials; target:CompanyFinancials; purchasePremium:number; cashConsideration:number; debtConsideration:number; stockConsideration:number; costSynergies:number; revenueSynergies:number; integrationCosts:number; financingRate:number; taxRate:number }
export interface AccretionDilutionAnalysis { buyerNetIncome:number; buyerShares:number; targetNetIncome:number; additionalInterest:number; foregoneInterest:number; newShares:number; synergies:number; integrationCosts:number; taxRate:number }
export interface IpoAnalysis { company:string; preMoneyEquityValue:number; primaryShares:number; secondaryShares:number; grossProceeds:number; underwritingFeeRate:number; impliedSharePrice:number }
export interface Deal { name:string; buyer:string; target:string; type:string; industry:string; estimatedValue:number; stage:DealStage; rationale:string; risk:string; bottleneck:string; nextAction:string; updated:string }
export interface PitchBook { title:string; type:string; description:string; updated:string; status:"Sample"|"Completed" }
export interface DealMistakeEntry { category:string; happened:string; wrong:string; missed:string; impact:string; learned:string; processChange:string; beforeAfter:string; assessment:string }

export const equityValue = (sharePrice:number, dilutedShares:number) => sharePrice*dilutedShares;
export const enterpriseValue = (equity:number,cash:number,debt:number,minority=0,preferred=0) => equity+debt+minority+preferred-cash;
export const impliedEquityValue = (ev:number,cash:number,debt:number,minority=0,preferred=0) => ev-debt-minority-preferred+cash;
export const safeMultiple = (numerator:number,denominator:number) => denominator ? numerator/denominator : 0;
export const sourcesUses = (model:SourcesAndUses) => { const sources=Object.values(model.sources).reduce((a,b)=>a+b,0); const uses=Object.values(model.uses).reduce((a,b)=>a+b,0); return {sources,uses,gap:sources-uses,balanced:Math.abs(sources-uses)<0.01}; };
export function dcf(assumptions:DcfAssumptions){ let revenue=assumptions.revenue; const cashFlows=assumptions.growthRates.map((growth,index)=>{ revenue*=1+growth; const ebitda=revenue*assumptions.ebitdaMargins[index]; const ebit=ebitda-assumptions.depreciation; return ebit*(1-assumptions.taxRate)+assumptions.depreciation-assumptions.capex-assumptions.changeNwc; }); const pvForecast=cashFlows.reduce((sum,fcf,index)=>sum+fcf/(1+assumptions.wacc)**(index+1),0); const terminalFcf=cashFlows.at(-1)??0; const terminalValue=terminalFcf*(1+assumptions.terminalGrowth)/(assumptions.wacc-assumptions.terminalGrowth); const pvTerminal=terminalValue/(1+assumptions.wacc)**cashFlows.length; const enterpriseValue=pvForecast+pvTerminal; const equityValue=enterpriseValue-assumptions.netDebt; return {cashFlows,pvForecast,terminalValue,pvTerminal,enterpriseValue,equityValue,sharePrice:equityValue/assumptions.dilutedShares}; }
export function leverage(structure:CapitalStructure,ebitda:number){ const grossDebt=structure.debt.reduce((s,d)=>s+d.principal,0); const interest=structure.debt.reduce((s,d)=>s+d.principal*d.interestRate,0); return {grossDebt,netDebt:grossDebt-structure.cash,grossLeverage:safeMultiple(grossDebt,ebitda),netLeverage:safeMultiple(grossDebt-structure.cash,ebitda),interestCoverage:safeMultiple(ebitda,interest),weightedRate:safeMultiple(interest,grossDebt),interest}; }
export function accretionDilution(a:AccretionDilutionAnalysis){ const standalone=a.buyerNetIncome/a.buyerShares; const pretaxAdjustments=a.synergies-a.additionalInterest-a.foregoneInterest-a.integrationCosts; const proFormaNetIncome=a.buyerNetIncome+a.targetNetIncome+pretaxAdjustments*(1-a.taxRate); const proFormaShares=a.buyerShares+a.newShares; const proFormaEps=proFormaNetIncome/proFormaShares; return {standaloneEps:standalone,proFormaNetIncome,proFormaShares,proFormaEps,accretion:(proFormaEps/standalone)-1,breakEvenSynergy:((standalone*proFormaShares-a.buyerNetIncome-a.targetNetIncome)/(1-a.taxRate))+a.additionalInterest+a.foregoneInterest+a.integrationCosts}; }

export const sampleCompany:CompanyFinancials={name:"Prism Industrial Systems",ticker:"PRSM",sharePrice:42,dilutedShares:100,cash:240,debt:860,minorityInterest:0,preferredStock:0,revenue:2400,ebitda:420,ebit:330,netIncome:210,freeCashFlow:260,growthRates:[.09,.08,.07,.06,.05],classification:"Sample"};
export const sampleComparables:ComparableCompany[]=[
 {company:"Aperture Systems",ticker:"APER",marketCap:5100,enterpriseValue:5600,revenue:2700,ebitda:510,revenueGrowth:.11,epsGrowth:.14,pe:22,roic:.13,netDebt:500,strength:"Strong"},
 {company:"Northstar Controls",ticker:"NSTC",marketCap:3900,enterpriseValue:4400,revenue:2300,ebitda:410,revenueGrowth:.08,epsGrowth:.1,pe:20,roic:.11,netDebt:500,strength:"Strong"},
 {company:"Vector Automation",ticker:"VCTA",marketCap:6100,enterpriseValue:6800,revenue:3100,ebitda:570,revenueGrowth:.13,epsGrowth:.16,pe:25,roic:.15,netDebt:700,strength:"Moderate"},
 {company:"Legacy Motion",ticker:"LGMO",marketCap:2100,enterpriseValue:2900,revenue:2600,ebitda:300,revenueGrowth:.02,epsGrowth:.03,pe:17,roic:.07,netDebt:800,strength:"Excluded",exclusionReason:"Lower-margin legacy product mix and materially different growth profile."}
];
export const samplePrecedents:PrecedentTransaction[]=[
 {announcementDate:"2025-09-18",buyer:"Atlas Holdings",target:"Motion Grid",industry:"Industrial technology",transactionValue:4800,enterpriseValue:4650,revenue:2100,ebitda:390,premium:.28,paymentMethod:"Cash",status:"Closed",rationale:"Automation portfolio expansion",similarity:88},
 {announcementDate:"2024-11-04",buyer:"Summit Corp.",target:"Delta Controls",industry:"Industrial technology",transactionValue:3600,enterpriseValue:3500,revenue:1900,ebitda:330,premium:.22,paymentMethod:"Cash / stock",status:"Closed",rationale:"Controls platform consolidation",similarity:81}
];
export const sampleDeals:Deal[]=[
 {name:"Project Aurora",buyer:"Prism Industrial",target:"Helio Automation",type:"Buy-side M&A",industry:"Industrials",estimatedValue:4700,stage:"Valuation",rationale:"Product expansion",risk:"Customer concentration",bottleneck:"Financing capacity",nextAction:"Complete lender case",updated:"2026-07-10"},
 {name:"Project Meridian",buyer:"Strategic buyer",target:"Northstar Analytics",type:"Sell-side",industry:"Software",estimatedValue:2200,stage:"Due Diligence",rationale:"Technology acquisition",risk:"Retention",bottleneck:"Quality of earnings",nextAction:"Resolve revenue cohort bridge",updated:"2026-07-08"},
 {name:"Project Vertex",buyer:"Public markets",target:"Vector Health",type:"IPO",industry:"Healthcare",estimatedValue:3100,stage:"Pitch Preparation",rationale:"Growth financing",risk:"Market window",bottleneck:"Profitability narrative",nextAction:"Finalize comps",updated:"2026-07-05"}
];
export const disclosure="Deal Lab content is provided for educational and portfolio-demonstration purposes only. Analyses may use estimates, hypothetical assumptions, delayed information, or sample data. Nothing presented constitutes investment banking, securities, lending, valuation, legal, tax, accounting, or transaction advice.";
