import Link from "next/link";
import { analysisCategories, commentary, research } from "@/lib/data";
import { Score, SectionHeading } from "@/components/site";

export default function Home(){return <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">Independent investment research · Shy Lee</span><h1>Price is the result.<br/><em>Prism reveals the causes.</em></h1><p>Independent investment research combining business fundamentals, institutional behavior, industry ecosystems, valuation, and Stage 2 price structure.</p><div className="button-row"><Link className="button primary" href="/research">Explore research <span>↗</span></Link><Link className="button" href="/luna1-framework">View the LUNA Framework <span>→</span></Link></div></div>
  <div className="prism-visual" aria-label="A price beam separating into analytical factors"><div className="ticker-beam">PRICE <b>→</b></div><div className="prism-shape">P</div><div className="spectrum-lines">{["Earnings","Revenue","Moat","Management","Institutions","Technicals","Valuation","Risk"].map((x,i)=><span key={x} style={{"--i":i} as React.CSSProperties}>{x}</span>)}</div><div className="visual-note">ONE PRICE · EIGHT UNDERLYING FORCES</div></div></section>
  <section><SectionHeading eyebrow="Featured research" title="Businesses worth understanding." copy="A focused library of company research, scored through the Prism lens."/><div className="research-grid">{research.slice(0,3).map(r=><Link href={`/research/${r.ticker.toLowerCase()}`} className="research-card" key={r.ticker}><div className="card-top"><div><span className="ticker">{r.ticker}</span><small>{r.industry}</small></div><Score score={r.score}/></div><h3>{r.company}</h3><p>{r.summary}</p><div className="card-meta"><span>{r.classification}</span><span>{r.date}</span></div></Link>)}</div></section>
  <section className="snapshot"><div><span className="eyebrow">Current portfolio snapshot</span><h2>Conviction, sized with discipline.</h2><p>Sample positions show how thesis, entry quality, and risk rules live together—not as separate decisions.</p><Link className="text-link" href="/portfolios">View portfolio methodology →</Link></div><div className="allocation"><div><span>Long-term holdings</span><b>46%</b></div><i style={{width:"46%"}}/><div><span>Active positions</span><b>31%</b></div><i style={{width:"31%"}}/><div><span>Opportunity reserve</span><b>23%</b></div><i style={{width:"23%"}}/><small>Illustrative allocation · not real-time portfolio data</small></div></section>
  <section><SectionHeading eyebrow="The Prism lens" title="Separate the signal from the price."/><div className="category-grid">{analysisCategories.map((x,i)=><div className="category-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Direction, acceleration, and quality of growth.","Conversion, leverage, and durability.","Why customers stay—and competitors struggle.","Decision quality across the cycle.","Bottlenecks, structure, and value-chain leverage.","Evidence of informed, sustained demand.","Stage, base quality, and entry timing.","Expectations, asymmetry, and invalidation."][i]}</p></div>)}</div></section>
  <section className="luna-preview"><div><span className="eyebrow">Multi-Factor Investment Research Framework</span><h2>LUNA separates price into the fundamentals that create it.</h2><p>Layered Understanding of Narrative Acceleration combines improving business fundamentals, institutional sponsorship, competitive advantage, and Stage 2 technical structure.</p><Link className="button primary" href="/luna1-framework">Explore LUNA <span>↗</span></Link></div><div className="orbit"><span>LUNA</span>{["Earnings","Revenue","Sponsors","Moat","Structure","Risk"].map((x,i)=><i key={x} style={{"--i":i} as React.CSSProperties}>{x}</i>)}</div></section>
  <section><SectionHeading eyebrow="Market journal" title="What changed—and what matters next."/><div className="commentary-grid">{commentary.map(x=><Link href={`/market-commentary/${x.slug}`} key={x.slug} className="article-card"><span className="eyebrow">{x.category} · {x.date}</span><h3>{x.title}</h3><p>{x.summary}</p><b>Read commentary →</b></Link>)}</div></section>
  <section className="philosophy-cta"><span className="eyebrow">Investment philosophy</span><blockquote>“A thesis is not a story to defend. It is a hypothesis to update as evidence changes.”</blockquote><Link href="/investment-philosophy">Read the principles →</Link></section>
  <section className="background"><SectionHeading eyebrow="Professional background" title="Research shaped by operations."/><div className="background-grid"><div><b>01</b><h3>U.S. Army veteran</h3><p>Discipline, logistics, financial management, and accountability.</p></div><div><b>02</b><h3>Data center operations</h3><p>Firsthand experience with mission-critical infrastructure.</p></div><div><b>03</b><h3>Finance & equity research</h3><p>Fundamental analysis at SDSU and the Aztec Investment Fund.</p></div></div></section>
  <section className="cta"><span className="eyebrow">Continue the conversation</span><h2>Look beyond the ticker.<br/>Reveal the business beneath the price.</h2><p>Follow new research, market observations, and updates to the LUNA Framework.</p><Link className="button primary" href="/contact">Contact Shy <span>↗</span></Link></section>
  </>}
