import type { Metadata } from "next";
import Link from "next/link";
import { setoraCompanyCandidates, setoraEventTypes, setoraVerticals } from "@/data/setora-alpha";
import { setoraNavigation } from "@/lib/setora";

export const metadata: Metadata = {
  title: "SETORA MAP | Capital Intelligence",
  description: "Map capital sources, catalysts, industries, companies, and second-order beneficiaries with source-aware research.",
};

export default function SetoraOverviewPage() {
  return <section className="setora-hero setora-overview"><div className="setora-hero-grid"><div><span className="setora-wordmark">SETORA <i>ALPHA</i></span><h1>Global capital intelligence across four connected verticals.</h1><p>SETORA is Luna1’s source-aware capital-chain system. It maps where capital is moving across physical AI, compute infrastructure, power systems, and financial rails, then preserves the evidence required to connect those systems responsibly.</p></div><div className="setora-refresh"><span>SETORA status</span><strong>Research foundation</strong><small>Independent from Luna1’s legacy equity-research universe</small></div></div><div className="setora-kpis" aria-label="SETORA scope"><article><span>Coverage candidates</span><strong>{setoraCompanyCandidates.length}</strong><p>Companies queued for primary-source research across the active infrastructure universe</p><small>SETORA universe · not recommendations</small></article><article><span>Primary verticals</span><strong>{setoraVerticals.length}</strong><p>Connected research surfaces from physical economy to financial infrastructure</p><small>SETORA taxonomy</small></article><article><span>Capital event types</span><strong>{setoraEventTypes.length}</strong><p>Discrete events the research feed can normalize</p><small>SETORA event schema</small></article><article><span>Cross-system lens</span><strong>1</strong><p>Capital map connecting robotics, compute, power, grid, defense, and finance</p><small>System view · review required</small></article></div><div className="setora-vertical-grid" aria-label="SETORA primary verticals">{setoraVerticals.map((vertical, index) => <article key={vertical.id}><span>{String(index + 1).padStart(2, "0")} · {vertical.status}</span><h2>{vertical.name}</h2><strong>{vertical.question}</strong><p>{vertical.description}</p><Link href="/setora/themes">Explore vertical research →</Link></article>)}</div><div className="setora-system-note"><span className="eyebrow">The system view</span><p>SETORA does not treat these as isolated sectors. Defense &amp; autonomy is a cross-cutting theme, while power and grid constraints connect physical AI, data centers, manufacturing, and the financial capital that funds them.</p><Link href="/setora/capital-map">Open the capital map →</Link></div><div className="setora-route-grid" aria-label="Explore SETORA">{setoraNavigation.slice(1).map(([label, href], index) => <Link href={href} key={href}><span>{String(index + 1).padStart(2, "0")}</span><h2>{label}</h2><b>Open page →</b></Link>)}</div></section>;
}
