import type { Metadata } from "next";
import Link from "next/link";
import { MetricCounter } from "@/components/research/metric-counter";
import { SectionHeading } from "@/components/site";
import {
  activePositions,
  krysFlywheel,
  krysMarginSeries,
  krysMetrics,
  krysMoat,
  krysMonitoring,
  krysSources,
} from "@/data/portfolio/active-positions";

export const metadata: Metadata = {
  title: "KRYS Position Research",
  description:
    "Educational position research on Krystal Biotech, VYJUVEK economics, operating leverage, platform optionality, and thesis-monitoring risks.",
};

const position = activePositions.find((item) => item.ticker === "KRYS");
const sources = Object.values(krysSources);
const progressionLabels = ["Q3 24", "Q4 24", "Q1 25", "Q2 25", "Q3 25", "Q4 25", "Q1 26", "Q2 26"];

function MarginChart({
  label,
  values,
  note,
}: {
  label: string;
  values: readonly number[];
  note: string;
}) {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const points = values
    .map((value, index) => {
      const x = (index / (values.length - 1)) * 100;
      const y = 82 - ((value - min) / range) * 62;
      return `${x},${y}`;
    })
    .join(" ");

  return (
    <article className="krys-progression-card">
      <header>
        <h3>{label}</h3>
        <strong>{values.at(-1)?.toFixed(2).replace(/\.00$/, "")}%</strong>
      </header>
      <svg viewBox="0 0 100 100" role="img" aria-label={`${label} progression`}>
        <polyline points={points} vectorEffect="non-scaling-stroke" />
        {values.map((value, index) => {
          const x = (index / (values.length - 1)) * 100;
          const y = 82 - ((value - min) / range) * 62;
          return <circle cx={x} cy={y} key={`${label}-${index}`} r="1.8" />;
        })}
      </svg>
      <div className="krys-periods" aria-hidden="true">
        {progressionLabels.map((period) => (
          <span key={period}>{period}</span>
        ))}
      </div>
      <p>{note}</p>
    </article>
  );
}

export default function KrysPositionResearch() {
  if (!position) return null;

  return (
    <>
      <section className="krys-hero">
        <Link className="text-link" href="/portfolio">
          ← Portfolio Lab
        </Link>
        <div className="krys-hero-grid">
          <div>
            <span className="eyebrow">Active Position · Last Updated Q2 2026</span>
            <h1>KRYS</h1>
            <h2>Krystal Biotech, Inc.</h2>
            <div className="topic-strip">
              <span>Healthcare</span>
              <span>Biotechnology</span>
              <span>Gene Therapy</span>
              <span>Commercial Stage</span>
            </div>
          </div>
          <aside>
            <span className="status" data-status="active-position">
              Active Position
            </span>
            <dl>
              <div>
                <dt>Position type</dt>
                <dd>{position.positionType}</dd>
              </div>
              <div>
                <dt>Position classification</dt>
                <dd>Commercial-Stage Growth Compounder</dd>
              </div>
              <div>
                <dt>LUNA classification</dt>
                <dd>Narrative Acceleration / Profitability Inflection</dd>
              </div>
            </dl>
          </aside>
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="Position Thesis" title="A commercial engine testing a platform thesis." />
        <p className="krys-lead">
          Krystal Biotech is transitioning from a development-stage biotechnology company into a profitable commercial genetic-medicine platform led by VYJUVEK, its approved treatment for dystrophic epidermolysis bullosa. VYJUVEK combines rare-disease economics, proprietary gene-delivery technology, in-house manufacturing, and a company-reported Q2 2026 gross margin of approximately 95%.
        </p>
        <p className="krys-lead">
          The central investment question is whether cash generated by VYJUVEK can fund additional pipeline programs without the dilution commonly associated with early-stage biotechnology companies—and whether the HSV-1 platform can ultimately support multiple approved products.
        </p>
      </section>

      <section>
        <SectionHeading eyebrow="Key Fundamentals" title="Profitability is reaching below gross profit." />
        <div className="krys-metric-grid">
          {krysMetrics.map((metric) => (
            <article key={metric.label}>
              <small>{metric.label}</small>
              <strong>
                <MetricCounter value={metric.numericValue} />
              </strong>
              <span className="data-label">{metric.type}</span>
              <p>{metric.note}</p>
              <a href={`#source-${metric.sourceId}`}>Source ↘</a>
            </article>
          ))}
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="Margin Progression" title="Direction matters more than a single quarter." />
        <div className="krys-progression-grid">
          {krysMarginSeries.map((series) => (
            <MarginChart key={series.label} {...series} />
          ))}
        </div>
        <p className="data-method-note">
          Progression series are manually entered Luna1 research calculations based on company filings. They are neither real-time data nor company-reported non-GAAP measures unless explicitly labeled.
        </p>
      </section>

      <section>
        <SectionHeading eyebrow="VYJUVEK Commercial Performance" title="The cash-generating engine." />
        <div className="krys-commercial-grid">
          <article>
            <small>FY2025 VYJUVEK revenue</small>
            <strong>$389.1M</strong>
            <p>Reported · fiscal year ended December 31, 2025</p>
            <a href="#source-fy2025-release">Source ↘</a>
          </article>
          <article>
            <small>Q1 2026 VYJUVEK revenue</small>
            <strong>$116.4M</strong>
            <p>Reported · approximately +32% year over year</p>
            <a href="#source-q1-release">Source ↘</a>
          </article>
          <article>
            <small>Q2 2026 VYJUVEK revenue</small>
            <strong>$119.2M</strong>
            <p>Reported · approximately +24% year over year</p>
            <a href="#source-q2-release">Source ↘</a>
          </article>
          <article>
            <small>Q2 2026 cost of goods sold</small>
            <strong>$6.4M</strong>
            <p>Reported · implies approximately 94.6% gross margin</p>
            <a href="#source-q2-release">Source ↘</a>
          </article>
        </div>
        <div className="krys-engine-bridge">
          <span>$119.2M revenue</span>
          <i aria-hidden="true" />
          <span>$6.4M COGS</span>
          <b>≈95% gross margin</b>
        </div>
        <p className="krys-lead">
          VYJUVEK provides Krystal with a profitable commercial engine capable of helping finance development of the company&apos;s broader genetic-medicine pipeline.
        </p>
      </section>

      <section>
        <SectionHeading eyebrow="Competitive Advantage" title="Why KRYS may have a moat." />
        <div className="krys-moat-grid">
          {krysMoat.map(([title, description], index) => (
            <article key={title}>
              <span>{String(index + 1).padStart(2, "0")}</span>
              <h3>{title}</h3>
              <p>{description}</p>
            </article>
          ))}
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="KRYS Platform Flywheel" title="Commercial success can fund the next test." />
        <div className="krys-flywheel" aria-label="KRYS Platform Flywheel">
          {krysFlywheel.map((step, index) => (
            <div key={step}>
              <span>{String(index + 1).padStart(2, "0")}</span>
              <strong>{step}</strong>
              {index < krysFlywheel.length - 1 && <i aria-hidden="true">↓</i>}
            </div>
          ))}
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="Luna1 Insight" title="Why the margin structure matters." />
        <div className="krys-insights">
          <blockquote>
            A 95% gross margin alone does not make KRYS attractive. The more important signal is that high gross margins are translating into approximately 49% operating margins and approximately 50% EBITDA margins while the company continues investing in its pipeline.
          </blockquote>
          <blockquote>
            The long-term question is whether one highly profitable commercial product can finance the creation of several additional successful products using the same underlying platform.
          </blockquote>
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="Growth Drivers" title="The evidence required for compounding." />
        <ul className="krys-driver-list">
          {[
            "Continued VYJUVEK adoption",
            "International VYJUVEK expansion",
            "Additional reimbursement coverage",
            "Increased physician adoption",
            "Manufacturing efficiencies",
            "Pipeline clinical progress",
            "Additional indications",
            "New product approvals",
            "Operating leverage",
            "Internal funding of R&D",
          ].map((driver) => (
            <li key={driver}>{driver}</li>
          ))}
        </ul>
      </section>

      <section>
        <SectionHeading eyebrow="What I Am Watching" title="A monitoring dashboard for thesis accountability." />
        <div className="krys-monitor-grid">
          {krysMonitoring.map(([title, question]) => (
            <article key={title}>
              <h3>{title}</h3>
              <p>{question}</p>
            </article>
          ))}
        </div>
      </section>

      <section>
        <SectionHeading eyebrow="Thesis Invalidation" title="What would materially weaken the case." />
        <div className="krys-invalidation">
          <p>{position.thesisInvalidation}</p>
        </div>
        <p className="data-method-note">
          Biotechnology investments retain substantial clinical, regulatory, reimbursement, manufacturing, competition, and product-concentration risk.
        </p>
      </section>

      <section>
        <SectionHeading eyebrow="Sources & Data Integrity" title="Reported facts remain separate from interpretation." />
        <div className="krys-source-list">
          {sources.map((source, index) => (
            <article id={`source-${source.id}`} key={source.id}>
              <span>{String(index + 1).padStart(2, "0")}</span>
              <div>
                <h3>{source.title}</h3>
                <p>{source.publisher} · {source.date} · {source.period}</p>
                <a href={source.url} target="_blank" rel="noreferrer">
                  Open primary source ↗
                </a>
              </div>
            </article>
          ))}
        </div>
        <div className="research-disclaimer">
          This position research is for educational and informational purposes only. It reflects personal analysis and opinions and is not investment, financial, tax, or legal advice. Data may be manually entered or delayed; calculations should be independently reproduced before use.
        </div>
      </section>
    </>
  );
}
