import {test,expect} from "@playwright/test";
test("primary pages load",async({page})=>{for(const path of ["/","/research","/portfolio-dashboard","/financial-models","/contact"]){await page.goto(path);await expect(page.locator("h1")).toBeVisible()}});
test("contact form and endpoint validate",async({page,request})=>{await page.goto("/contact");await expect(page.getByRole("button",{name:"Request connection"})).toBeVisible();const response=await request.post("/api/contact",{data:{name:"Research Visitor",organization:"Example Organization",reason:"Research discussion",message:"I would like to discuss the educational research methodology."}});expect(response.ok()).toBeTruthy()});

test("opens the JBL decision review",async({page})=>{await page.goto("/portfolio-dashboard");await page.getByRole("tab",{name:"Mistake Journal"}).click();await expect(page.getByText("Jabil Inc.")).toBeVisible();await page.getByRole("button",{name:"View Review"}).click();await expect(page.getByRole("dialog",{name:/JBL/})).toBeVisible();await expect(page.getByRole("heading",{name:"Final Assessment"})).toBeVisible();await page.getByRole("button",{name:"Close JBL decision review"}).click();await expect(page.getByRole("dialog")).toHaveCount(0)});

test("filters Mistake Journal decisions",async({page})=>{await page.goto("/portfolio-dashboard");await page.getByRole("tab",{name:"Mistake Journal"}).click();await page.getByLabel("Classification").selectOption("Failed Thesis");await expect(page.getByRole("status")).toContainText("no decisions");await page.getByRole("button",{name:"Reset filters"}).first().click();await expect(page.getByText("Jabil Inc.")).toBeVisible()});

test("Mistake Journal table becomes cards on mobile",async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto("/portfolio-dashboard");await page.getByRole("tab",{name:"Mistake Journal"}).click();const row=page.locator(".journal-table tbody tr").first();await expect(row).toBeVisible();await expect.poll(()=>row.evaluate((element)=>getComputedStyle(element).display)).toBe("block");await expect(page.getByRole("button",{name:"View Review"})).toBeVisible()});
