import {test,expect,type Locator} from "@playwright/test";

async function activate(locator:Locator,projectName:string){
  if(projectName==="mobile"){
    await locator.tap();
    return;
  }
  await locator.click();
}
test("primary pages load",async({page})=>{for(const path of ["/","/research","/portfolio-dashboard","/financial-models","/contact"]){await page.goto(path);await expect(page.locator("h1")).toBeVisible()}});
test("educational disclosure is globally visible",async({page})=>{await page.goto("/");await expect(page.getByText("Educational Disclosure:",{exact:true})).toBeVisible();await expect(page.getByText("The information on Luna1 Research is provided for educational and informational purposes only.",{exact:false})).toBeVisible()});
test("brand assets page exposes working downloads on desktop and mobile",async({page,request})=>{await page.goto("/brand");await expect(page.getByRole("heading",{name:"Brand Assets"})).toBeVisible();const links=page.locator("a[download]");await expect(links).toHaveCount(8);for(const href of await links.evaluateAll(nodes=>nodes.map(node=>node.getAttribute("href")))){expect(href).toBeTruthy();const response=await request.get(href!);expect(response.ok(),`${href} should download`).toBeTruthy()}await page.setViewportSize({width:390,height:844});await page.reload();const first=await page.locator(".brand-card").nth(0).boundingBox();const second=await page.locator(".brand-card").nth(1).boundingBox();expect(first).not.toBeNull();expect(second).not.toBeNull();expect(first!.x).toBeGreaterThanOrEqual(0);expect(first!.x+first!.width).toBeLessThanOrEqual(page.viewportSize()!.width);expect(second!.y).toBeGreaterThan(first!.y+first!.height-1);await expect(page.getByRole("link",{name:/Download Brand Kit/})).toBeVisible()});
test("Deal Lab is not publicly exposed",async({page,request})=>{await page.goto("/");await expect(page.getByRole("navigation",{name:"Primary navigation"}).getByRole("link",{name:"Deal Lab"})).toHaveCount(0);const response=await request.get("/deal-lab");expect(response.status()).toBe(404)});
test("contact form and endpoint validate",async({page,request})=>{await page.goto("/contact");await expect(page.getByLabel("Name")).toBeVisible();await expect(page.getByLabel("Email")).toBeVisible();await expect(page.getByLabel("Subject")).toBeVisible();await expect(page.getByRole("button",{name:"Request connection"})).toBeVisible();const invalid=await request.post("/api/contact",{data:{name:"Research Visitor",email:"not-an-email",subject:"Research discussion",message:"I would like to discuss the educational research methodology."}});expect(invalid.status()).toBe(400);const spam=await request.post("/api/contact",{data:{name:"Research Visitor",email:"visitor@example.com",subject:"Research discussion",message:"I would like to discuss the educational research methodology.",website:"https://spam.example"}});expect(spam.ok()).toBeTruthy()});

test("contact form does not report success when email delivery is unconfigured",async({page},testInfo)=>{await page.goto("/contact");await page.waitForLoadState("networkidle");await page.getByLabel("Name").fill("Research Visitor");await page.getByLabel("Email").fill("visitor@example.com");await page.getByLabel("Organization").fill("Example Organization");await page.getByLabel("Subject").fill("Research discussion");await page.getByLabel("Message").fill("I would like to discuss the educational research methodology.");await activate(page.getByRole("button",{name:"Request connection"}),testInfo.project.name);await expect(page.locator(".contact-form").getByRole("alert")).toContainText("could not be sent");await expect(page.getByText("Thank you. Your message has been sent.")).toHaveCount(0)});

test("contact endpoint rate-limits repeated submissions",async({request},testInfo)=>{const data={name:"Rate Limit Test",email:"rate-limit@example.com",subject:"Rate limit validation",message:"This safe automated message verifies the contact endpoint rate limit."};const testIp=testInfo.project.name==="mobile"?"198.51.100.43":"198.51.100.42";for(let attempt=0;attempt<5;attempt++){const response=await request.post("/api/contact",{data,headers:{"x-forwarded-for":testIp}});expect(response.status()).toBe(503)}const limited=await request.post("/api/contact",{data,headers:{"x-forwarded-for":testIp}});expect(limited.status()).toBe(429);expect(limited.headers()["retry-after"]).toBeTruthy()});

test("resume combines the founder and recruiter profiles",async({page})=>{await page.goto("/resume");await expect(page.getByText("Shy Lee · Founder")).toBeVisible();await expect(page.getByAltText("Portrait of Shy Lee, founder of Luna1 Research")).toBeVisible();await expect(page.getByText("Infrastructure, Compounders, Inflections, Bottle Neck Constraint Analysis")).toBeVisible();await expect(page.getByRole("heading",{name:"Analysis grounded in accountable execution."})).toBeVisible();await expect(page.getByText("Microsoft Excel").locator("..")).toContainText("Completed");const navigation=page.getByRole("navigation",{name:"Primary navigation"});await expect(navigation.getByText("Market Commentary")).toHaveCount(0);await expect(navigation.getByText("Recruiter Portal")).toHaveCount(0);await page.goto("/recruiter");await expect(page).toHaveURL(/\/resume$/)});

test("watchlist displays approved research detail without overflow",async({page},testInfo)=>{await page.goto("/portfolios");await activate(page.getByRole("tab",{name:"Watchlist"}),testInfo.project.name);for(const ticker of ["AIPO","GLW","STRL","ALAB","JBL","RY","PANW","PDFS","ANET","WWD","AMAT","GS"])await expect(page.getByText(ticker,{exact:true}).first()).toBeVisible();await expect(page.getByLabel("LUNA Score 95 out of 100")).toBeVisible();await expect(page.getByText("Arista Networks is a leading AI and cloud-networking business",{exact:false})).toBeVisible();await expect(page.getByText("Accelerating Ethernet-based AI networking",{exact:false})).toBeVisible();await expect(page.getByText("Hyperscaler concentration, competition",{exact:false})).toBeVisible();await expect(page.getByText("ROAD",{exact:true})).toHaveCount(0);if(testInfo.project.name==="mobile"){const row=page.locator(".watchlist-table tbody tr").first();await expect.poll(()=>row.evaluate(element=>getComputedStyle(element).display)).toBe("block");const box=await row.boundingBox();expect(box).not.toBeNull();expect(box!.x+box!.width).toBeLessThanOrEqual(page.viewportSize()!.width)}});

test("opens the JBL decision review",async({page},testInfo)=>{await page.goto("/portfolio-dashboard");await page.waitForLoadState("networkidle");await activate(page.getByRole("tab",{name:"Mistake Journal"}),testInfo.project.name);await expect(page.getByText("Jabil Inc.")).toBeVisible();await activate(page.getByRole("button",{name:"View Review"}),testInfo.project.name);await expect(page.getByRole("dialog",{name:/JBL/})).toBeVisible();await expect(page.getByRole("heading",{name:"Final Assessment"})).toBeVisible();await activate(page.getByRole("button",{name:"Close JBL decision review"}),testInfo.project.name);await expect(page.getByRole("dialog")).toHaveCount(0)});

test("filters Mistake Journal decisions",async({page},testInfo)=>{await page.goto("/portfolio-dashboard");await page.waitForLoadState("networkidle");await activate(page.getByRole("tab",{name:"Mistake Journal"}),testInfo.project.name);await page.getByLabel("Classification").selectOption("Failed Thesis");await expect(page.getByRole("status")).toContainText("no decisions");await activate(page.getByRole("button",{name:"Reset filters"}).first(),testInfo.project.name);await expect(page.getByText("Jabil Inc.")).toBeVisible()});

test("commercial is not publicly exposed",async({page,request})=>{await page.goto("/");await expect(page.getByText("Luna1 cinematic teaser",{exact:false})).toHaveCount(0);await expect(page.getByRole("link",{name:/full commercial/i})).toHaveCount(0);const response=await request.get("/commercial");expect(response.status()).toBe(404)});

test("Mistake Journal table becomes cards on mobile",async({page},testInfo)=>{await page.setViewportSize({width:390,height:844});await page.goto("/portfolio-dashboard");await page.waitForLoadState("networkidle");await activate(page.getByRole("tab",{name:"Mistake Journal"}),testInfo.project.name);const row=page.locator(".journal-table tbody tr").first();await expect(row).toBeVisible();await expect.poll(()=>row.evaluate((element)=>getComputedStyle(element).display)).toBe("block");await expect(page.getByRole("button",{name:"View Review"})).toBeVisible()});
