import type { Metadata } from "next";
import Link from "next/link";
import { RecruiterActions } from "@/components/recruiter-actions";
import { research } from "@/lib/data";

export const metadata: Metadata = { title: "Recruiter Portal", description: "Recruiter profile for Shy Lee: finance, equity research, operations, and military experience." };

const experience = [
  ["2026-Present", "Coronado Historical Association", "Executive & Finance Assistant", "Accrual accounting support, reconciliations, reporting schedules, board materials, and audit-ready nonprofit finance documentation."],
  ["2020-Present", "LightEdge Solutions", "Data Center Network Operations Technician", "Mission-critical infrastructure operations, service coordination, asset controls, compliance records, and cross-functional issue resolution."],
  ["2015-2019", "United States Army", "Supply Specialist & Financial Management Technician", "Aviation and ground logistics, accountable inventory, budgeting support, reconciliations, and reporting across more than $10 million in operational expenditures."],
  ["2014-2015", "Wilgus Associates", "Junior Reconciliation Accountant", "Ledger maintenance, bank reconciliations, variance investigation, month-end support, and automation that reduced reconciliation time by 50%."],
] as const;
const models = [["Discounted cash flow", "Revenue, margin, tax, discount-rate, and terminal-growth sensitivities."], ["Comparable companies", "Peer multiples organized around growth, profitability, cash conversion, and expectations."], ["Scenario analysis", "Base, upside, and downside cases with explicit catalysts, risks, and invalidation points."]] as const;

export default function RecruiterPortal() { return <>
  <section className="recruiter-hero"><div><span className="eyebrow">Recruiter portal · Shy Lee</span><p className="recruiter-status"><i /> Open to finance, investment research, and analyst opportunities</p><h1>Finance discipline.<br/><em>Operational perspective.</em></h1><p className="recruiter-lead">U.S. Army veteran and finance professional combining equity research, accounting, financial analysis, and five-plus years inside mission-critical data center operations.</p><RecruiterActions /></div><aside className="recruiter-brief" aria-label="Candidate snapshot"><span className="eyebrow">Candidate brief</span><dl><div><dt>Focus</dt><dd>Equity research · FP&amp;A · Finance</dd></div><div><dt>Education</dt><dd>B.S. Finance, expected 2027</dd></div><div><dt>Experience</dt><dd>Accounting · Operations · Military</dd></div><div><dt>Research lens</dt><dd>Fundamentals · Valuation · Risk</dd></div><div><dt>Availability</dt><dd>Professional inquiries via contact form</dd></div></dl></aside></section>
  <nav className="recruiter-index" aria-label="Recruiter portal sections">{["Summary","Experience","Education","Certifications","Research","Projects","Models","Philosophy","Portfolio","Journal","Timeline","Contact"].map(label => <a key={label} href={`#${label.toLowerCase()}`}>{label}</a>)}</nav>
  <section id="summary" className="recruiter-split"><div><span className="eyebrow">Professional summary</span><h2>Analysis grounded in accountable execution.</h2></div><div><p className="recruiter-pull">I translate complex operating and financial information into clear decisions, with a process shaped by military accountability, hands-on infrastructure work, and fundamental investment research.</p><p>My work connects financial statements to the business beneath them: revenue drivers, margin structure, capital allocation, industry constraints, valuation, and the evidence that would change a thesis.</p></div></section>
  <section id="experience"><header className="recruiter-section-head"><span className="eyebrow">Experience</span><h2>Professional experience</h2></header><div className="recruiter-timeline">{experience.map(([date,company,title,copy],i)=><article key={company}><span className="recruiter-number">0{i+1}</span><time>{date}</time><div><h3>{company}</h3><b>{title}</b><p>{copy}</p></div></article>)}</div></section>
  <section className="recruiter-duo"><div id="education"><span className="eyebrow">Education</span><h2>Finance foundation</h2><div className="credential"><b>SDSU</b><span>Fowler College of Business</span><p>Bachelor of Science in Finance · Expected 2027</p></div><div className="credential"><b>Miramar College</b><p>Associate of Science in Business Administration · 2024</p></div><div className="credential"><b>Aztec Investment Fund</b><p>Fundamental equity research and investment-thesis development, including an AI infrastructure thesis informed by data center operating experience.</p></div></div><div id="certifications"><span className="eyebrow">Certifications</span><h2>Applied development</h2><div className="credential-list"><div><b>QuickBooks Online Level 1</b><span>Completed</span></div><div><b>Bloomberg Market Concepts</b><span>Completed</span></div><div><b>Microsoft Excel</b><span>In progress</span></div><div><b>SIE</b><span>Planned</span></div><div><b>FMVA</b><span>Planned</span></div></div><Link className="text-link" href="/certifications">View certification roadmap →</Link></div></section>
  <section id="research"><header className="recruiter-section-head"><span className="eyebrow">Featured research</span><h2>Businesses worth understanding.</h2><p>Illustrative research records demonstrate the structure of the Luna1 process; values are not real-time market data.</p></header><div className="recruiter-research">{research.slice(0,3).map((item,i)=><Link href={`/research/${item.ticker.toLowerCase()}`} key={item.ticker}><span>0{i+1} · {item.industry}</span><h3>{item.ticker} / {item.company}</h3><p>{item.catalyst}</p><b>{item.classification} →</b></Link>)}</div></section>
  <section id="projects" className="recruiter-duo recruiter-projects"><div><span className="eyebrow">Python projects</span><h2>Tools that make analysis repeatable.</h2><div className="project-card"><b>Resume document pipeline</b><p>Programmatic generation of a recruiter-ready resume with consistent typography, spacing, and privacy-safe contact routing.</p><span>Python · ReportLab · PDF validation</span></div><div className="project-card"><b>One-page profile generator</b><p>A compact two-column candidate brief generated from structured professional, education, research, and skills content.</p><span>Python · structured content · print layout</span></div></div><div id="models"><span className="eyebrow">Financial models</span><h2>Valuation with visible assumptions.</h2>{models.map(([title,copy],i)=><div className="model-line" key={title}><span>0{i+1}</span><div><b>{title}</b><p>{copy}</p></div></div>)}<Link className="text-link" href="/financial-models">Explore financial models →</Link></div></section>
  <section id="philosophy" className="recruiter-quote"><span className="eyebrow">Investment philosophy</span><blockquote>“A thesis is not a story to defend. It is a hypothesis to update as evidence changes.”</blockquote><p>Start with business change. Test it through earnings, competitive position, institutional recognition, valuation, technical structure, and explicit risk rules.</p><Link className="text-link" href="/investment-philosophy">Read the full philosophy →</Link></section>
  <section id="portfolio" className="recruiter-split"><div><span className="eyebrow">Portfolio</span><h2>Conviction made accountable.</h2></div><div><p className="recruiter-pull">Every position begins with a written thesis, an evidence checklist, a defined add level, and a clear invalidation rule.</p><p>Public portfolio examples are manually updated and educational only. They do not represent real-time brokerage data or personalized investment advice.</p><Link className="button" href="/portfolios">View portfolio methodology <span>→</span></Link></div></section>
  <section id="journal"><header className="recruiter-section-head"><span className="eyebrow">Mistake journal</span><h2>Process improves when errors become data.</h2></header><div className="journal-method"><div><span>01</span><b>Record</b><p>Capture the decision, evidence available, and emotional context without rewriting history.</p></div><div><span>02</span><b>Classify</b><p>Separate analytical, sizing, timing, execution, and process errors.</p></div><div><span>03</span><b>Correct</b><p>Translate the lesson into a checklist, threshold, or repeatable portfolio rule.</p></div></div></section>
  <section id="timeline"><header className="recruiter-section-head"><span className="eyebrow">Timeline</span><h2>A career built across finance and operations.</h2></header><div className="career-line"><div><time>2014</time><b>Accounting</b></div><div><time>2015</time><b>U.S. Army</b></div><div><time>2020</time><b>Data centers</b></div><div><time>2024</time><b>Business degree</b></div><div><time>2026</time><b>Finance &amp; research</b></div><div><time>2027</time><b>B.S. Finance</b></div></div></section>
  <section id="contact" className="recruiter-contact"><div><span className="eyebrow">Contact</span><h2>Start a professional conversation.</h2><p>Recruiting inquiries are welcome through the secure site contact form. Private contact details are intentionally not published.</p></div><Link className="button primary" href="/contact">Contact Shy <span>↗</span></Link></section>
</>; }
