"use client";
import { useEffect, useState } from "react";
import type { MarketNewsResponse } from "@/lib/market-news";
const empty: MarketNewsResponse = { headlines: [], status: "unavailable", updatedAt: null, provider: "Financial Modeling Prep" };
export function MarketHeadlines() {
  const [data, setData] = useState<MarketNewsResponse>(empty); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; const load = async () => { if (document.visibilityState === "hidden") return; try { const response = await fetch("/api/market-news", { cache: "no-store" }); const payload = await response.json() as MarketNewsResponse; if (active) setData(payload); } catch { if (active) setData((current) => ({ ...current, status: "unavailable", message: "Market headlines are temporarily unavailable." })); } finally { if (active) setLoading(false); } }; void load(); const timer = window.setInterval(() => void load(), 300_000); const onVisibility = () => { if (document.visibilityState === "visible") void load(); }; document.addEventListener("visibilitychange", onVisibility); return () => { active = false; window.clearInterval(timer); document.removeEventListener("visibilitychange", onVisibility); }; }, []);
  return <section className="market-headlines-strip" aria-labelledby="market-headlines-title"><div className="market-headlines-label"><h2 id="market-headlines-title">Market Headlines</h2><small>Live news</small></div><div className="market-headlines-list" aria-live="polite">{loading ? <span>Loading headlines…</span> : data.headlines.length ? data.headlines.map((headline) => <a key={`${headline.url}-${headline.publishedAt}`} href={headline.url} target="_blank" rel="noreferrer"><span>{headline.title}</span><small>{headline.source} · {new Date(headline.publishedAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", timeZone: "America/New_York" })} ET</small></a>) : <span>{data.message ?? "Market headlines unavailable"}</span>}</div></section>;
}
