"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { navigationItems } from "@/lib/data";

export function LunaMark() { return <span className="mark" aria-hidden="true"><i/><i/><i/></span> }
export function Navbar() {
  const path = usePathname(); const [open,setOpen]=useState(false); const [dark,setDark]=useState(true); const menuButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{const stored=window.localStorage.getItem("theme");setDark(stored?stored==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches)});return()=>cancelAnimationFrame(frame)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";window.localStorage.setItem("theme",dark?"dark":"light")},[dark]);
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);menuButton.current?.focus()}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open]);
  return <header className="nav"><div className="nav-inner"><Link className="brand" href="/" onClick={()=>setOpen(false)}><LunaMark/><span>LUNA1 RESEARCH</span></Link>
    <nav className="desktop-nav" aria-label="Primary navigation">{navigationItems.map(i=><Link className={path===i.href||i.href!=="/"&&path.startsWith(i.href)?"active":""} key={i.href} href={i.href}>{i.label}</Link>)}</nav>
    <div className="nav-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?"light":"dark"} theme`} aria-pressed={dark}>{dark?"☼":"◐"}</button><button ref={menuButton} className="menu-button" aria-expanded={open} aria-controls="mobile-navigation" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?"Close":"Menu"}</button></div>
  </div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{navigationItems.map(i=><Link key={i.href} className={path===i.href||i.href!=="/"&&path.startsWith(i.href)?"active":""} href={i.href} onClick={()=>setOpen(false)}>{i.label}</Link>)}</nav>}</header>
}
export function Footer(){return <footer><div className="footer-main"><div><Link className="brand" href="/"><LunaMark/><span>LUNA1 RESEARCH</span></Link><p>Institutional-quality independent research by Shyheim Lee.</p></div><div><span className="eyebrow">Navigate</span><p><Link href="/research">Research</Link> · <Link href="/luna1-framework">Framework</Link> · <Link href="/contact">Contact</Link></p></div><div><span className="eyebrow">Professional inquiries</span><p>Available through the <Link href="/contact">contact form</Link>.</p></div></div><div className="disclaimer">Luna1 Research contains independent research and educational commentary. Nothing on this website constitutes personalized investment advice, a recommendation, or an offer to buy or sell securities. All investments involve risk, including loss of principal.</div><div className="copyright">© 2026 Luna1 Research. All rights reserved. <Link className="footer-brand-link" href="/brand">Brand Assets</Link></div></footer>}
export function PageHeader({kicker,title,description}:{kicker:string,title:string,description:string}){return <section className="page-header"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{description}</p></section>}
export function SectionHeading({eyebrow,title,copy}:{eyebrow:string,title:string,copy?:string}){return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function Score({score}:{score:number}){return <div className="score" aria-label={`LUNA Score ${score} out of 100`}><span>{score}</span><small>LUNA<br/>SCORE</small></div>}
export function Scorecard(){const [values,setValues]=useState([25,20,12,12,8,4]);const total=values.reduce((a,b)=>a+b,0);const labels=["Fundamentals","Technical structure","Institutional behavior","Moat & industry","Catalyst & runway","Risk & entry"];const max=[30,25,15,15,10,5];return <div className="scorecard"><div className="score-total"><Score score={total}/><div><span className="eyebrow">Illustrative ticker · LUNA</span><h3>{total>=90?"LUNA Superleader":total>=80?"LUNA-A":total>=70?"LUNA-B / Inflection Leader":total>=60?"Watchlist":"Does Not Qualify"}</h3></div></div>{labels.map((l,i)=><label className="range-row" key={l}><span>{l}</span><input aria-label={l} type="range" min="0" max={max[i]} value={values[i]} onChange={e=>setValues(values.map((v,j)=>j===i?+e.target.value:v))}/><b>{values[i]}/{max[i]}</b></label>)}</div>}
export function DcfCalculator(){const [rev,setRev]=useState(1200),[growth,setGrowth]=useState(12),[margin,setMargin]=useState(22),[tax,setTax]=useState(21),[discount,setDiscount]=useState(9),[terminal,setTerminal]=useState(3),[shares,setShares]=useState(100);const fcf=rev*(1+growth/100)*margin/100*(1-tax/100);const ev=fcf*(1+terminal/100)/(discount/100-terminal/100);const per=ev/shares;const fields:[[string,number,(n:number)=>void,string],...Array<[string,number,(n:number)=>void,string]>]=[["Revenue",rev,setRev,"$m"],["Revenue growth",growth,setGrowth,"%"],["Operating margin",margin,setMargin,"%"],["Tax rate",tax,setTax,"%"],["Discount rate",discount,setDiscount,"%"],["Terminal growth",terminal,setTerminal,"%"],["Shares outstanding",shares,setShares,"m"]];return <div className="dcf"><div className="dcf-inputs">{fields.map(([l,v,s,u])=><label key={l}>{l}<span><input type="number" value={v} onChange={e=>s(+e.target.value)}/><b>{u}</b></span></label>)}</div><div className="dcf-results"><span className="eyebrow">Illustrative output</span><div><small>Enterprise value</small><strong>${Math.round(ev).toLocaleString()}m</strong></div><div><small>Equity value*</small><strong>${Math.round(ev).toLocaleString()}m</strong></div><div className="implied"><small>Implied value / share</small><strong>${per.toFixed(2)}</strong></div><p>*Assumes zero net debt for this simplified educational model.</p></div></div>}
